In [66]:
import pandas as pd
import numpy as np

In [67]:
raw_csv_data = pd.read_csv("Absenteeism-data.csv", delimiter=",")

In [133]:
raw_csv_data.head(20)

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,3,23,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,10,22,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,20,23,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,14,19,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,1,22,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,20,1,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,20,1,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,20,11,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,3,11,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,24,14,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,3,23,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,3,21,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,6,11,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,33,23,05/08/2015,248,25,47,205.917,32,1,2,1,2

In [69]:
df = raw_csv_data.copy()

In [70]:
#pd.options.display.max_columns = None
#pd.options.display.max_rows= None

In [134]:
df.head(20)

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,False,False,False,True,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,False,False,False,True,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,False,False,False,True,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,False,False,True,False,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,False,False,False,True,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,True,False,False,False,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,True,False,False,False,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,True,False,False,False,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,True,False,False,False,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,True,False,False,False,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,False,False,False,True,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,False,False,True,False,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,True,False,False,False,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,False,False,False,True,05/08/2015,248,25,47,205.917,32,1,2,1,2

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         700 non-null    int64
 1   Reason for Absence         700 non-null    int64
 2   Date                       700 non-null    object
 3   Transportation Expense     700 non-null    int64
 4   Distance to Work           700 non-null    int64
 5   Age                        700 non-null    int64
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64
 8   Education                  700 non-null    int64
 9   Children                   700 non-null    int64
 10  Pets                       700 non-null    int64
 11  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB

In [73]:
df = df.drop(['ID'],axis = 1)

In [132]:
df.head(20)

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,False,False,False,True,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,False,False,False,True,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,False,False,False,True,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,False,False,True,False,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,False,False,False,True,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,True,False,False,False,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,True,False,False,False,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,True,False,False,False,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,True,False,False,False,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,True,False,False,False,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,False,False,False,True,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,False,False,True,False,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,True,False,False,False,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,False,False,False,True,05/08/2015,248,25,47,205.917,32,1,2,1,2

In [75]:
df['Reason for Absence'].min()

0

In [76]:
df['Reason for Absence'].max()

28

In [77]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [78]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [79]:
len(df['Reason for Absence'].unique())

28

In [80]:
sorted(df['Reason for Absence'].unique())

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(28)]

In [81]:
reason_columns = pd.get_dummies(df['Reason for Absence'])

In [131]:
reason_columns.head(20)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,check
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,1
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,1
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,1
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,1
10,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
11,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
12,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
13,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
15,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,1
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,1
18,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1

In [130]:
reason_columns['check'] = reason_columns.sum(axis=1)
reason_columns.head(20)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,check
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,1
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,1
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,1
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,1
10,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
11,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
12,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
13,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
15,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,1
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,1
18,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1

In [84]:
reason_columns['check'].sum(axis=0)

np.int64(700)

In [85]:
reason_columns['check'].unique()

array([1])

In [135]:
reason_columns = reason_columns.drop(['check'], axis=1)
reason_columns.head(20)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
10,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [87]:
reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first=True)

In [129]:
reason_columns.head(20)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
10,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [89]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [90]:
reason_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28])

In [91]:
df = df.drop(['Reason for Absence'], axis=1)

In [136]:
reason_columns.loc[:, 1:14].max(axis=1).head(20)

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
12     True
13     True
14    False
15     True
16    False
17    False
18     True
19    False
dtype: bool

In [93]:
reason_type_1=reason_columns.loc[:, 1:14].max(axis=1)
reason_type_2=reason_columns.loc[:, 15:17].max(axis=1)
reason_type_3=reason_columns.loc[:, 18:21].max(axis=1)
reason_type_4=reason_columns.loc[:, 22:].max(axis=1)

In [128]:
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [95]:
df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3,reason_type_4],axis=1)
df

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,0,1,2,3
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,False,False,False,True
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,False,False,False,False
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,False,False,False,True
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,True,False,False,False
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,False,False,False,True
5,10/07/2015,179,51,38,239.554,31,1,0,0,2,False,False,False,True
6,17/07/2015,361,52,28,239.554,27,1,1,4,8,False,False,False,True
7,24/07/2015,260,50,36,239.554,23,1,4,0,4,False,False,False,True
8,06/07/2015,155,12,34,239.554,25,1,2,0,40,False,False,True,False
9,13/07/2015,235,11,37,239.554,29,3,1,1,8,False,False,False,True
10,20/07/2015,260,50,36,239.554,23,1,4,0,8,True,False,False,False
11,14/07/2015,260,50,36,239.554,23,1,4,0,8,True,False,False,False
12,15/07/2015,260,50,36,239.554,23,1,4,0,8,True,False,False,False
13,15/07/2015,179,51,38,239.554,31,1,0,0,1,True,False,False,False
14,15/07/2015,179,51,38,239.554,31,1,0,0,4,False,False,False,True
15,17/07/2015,246,25,41,239.554,23,1,0,0,8,True,False,False,False
16,17/07/2015,179,51,38,239.554,31,1,0,0,2,False,False,False,True
17,27/07/2015,179,51,38,239.554,31,1,0,0,8,False,False,True,False
18,30/07/2015,189,29,33,239.554,25,1,2,2,8,True,False,False,False
19,05/08/2015,248,25,47,205.917,32,1,2,1,2,False,False,False,True
20,12/08/2015,330,16,28,205.917,25,2,0,0,8,True,False,False,False
21,03/08/2015,179,51,38,205.917,31,1,0,0,1,True,False,False,False
22,10/08/2015,361,52,28,205.917,27,1,1,4,40,True,False,False,False
23,14/08/2015,260,50,36,205.917,23,1,4,0,4,False,False,False,True
24,17/08/2015,289,36,33,205.917,30,1,2,1,8,False,False,True,False
25,24/08/2015,361,52,28,205.917,27,1,1,4,7,False,False,False,True
26,04/08/2015,289,36,33,205.917,30,1,2,1,1,False,False,False,True
27,12/08/2015,157,27,29,205.917,22,1,0,0,4,False,False,False,True
28,19/08/2015,289,36,33,205.917,30,1,2,1,8,False,False,True,False
29,28/08/2015,179,51,38,205.917,31,1,0,0,2,False,False,False,True
30,17/08/2015,179,51,38,205.917,31,1,0,0,8,False,False,True,False
31,27/08/2015,235,29,48,205.917,33,1,1,5,8,False,False,True,False
32,27/08/2015,235,11,37,205.917,29,3,1,1,4,False,False,False,True
33,17/08/2015,235,29,48,205.917,33,1,1,5,8,False,False,True,False
34,17/08/2015,179,51,38,205.917,31,1,0,0,2,False,False,False,True
35,17/08/2015,361,52,28,205.917,27,1,1,4,1,False,False,False,True
36,04/08/2015,289,36,33,205.917,30,1,2,1,8,False,False,False,True
37,20/08/2015,291,50,32,205.917,23,1,0,0,4,True,False,False,False
38,21/08/2015,235,29,48,205.917,33,1,1,5,8,False,False,False,True
39,28/08/2015,260,50,36,205.917,23,1,4,0,4,False,False,False,True
40,01/09/2015,184,42,27,241.476,21,1,0,0,2,False,False,False,True
41,07/09/2015,118,10,37,241.476,28,1,0,0,4,False,False,False,True
42,01/09/2015,179,51,38,241.476,31,1,0,0,4,False,False,False,True
43,08/09/2015,235,20,43,241.476,38,1,1,0,8,False,False,True,False
44,09/09/2015,155,12,34,241.476,25,1,2,0,2,False,False,False,True
45,13/09/2015,118,10,37,241.476,28,1,0,0,3,False,False,False,True
46,14/09/2015,179,51,38,241.476,31,1,0,0,3,False,False,False,True
47,24/09/2015,291,31,40,241.476,25,1,1,1,4,False,False,False,True
48,04/09/2015,260,50,36,241.476,23,1,4,0,8,False,False,False,True
49,14/09/2015,291,31,40,241.476,25,1,1,1,32,True,False,False,False
50,21/09/2015,260,50,36,241.476,23,1,4,0,0,False,False,False,False
51,28/09/2015,225,26,28,241.476,24,1,1,2,0,False,False,False,False
52,08/09/2015,225,26,28,241.476,24,1,1,2,2,False,False,False,True
53,15/09/2015,118,10,37,241.476,28,1,0,0,2,False,False,False,True
54,22/09/2015,289,36,33,241.476,30,1,2,1,0,False,False,False,False
55,29/09/2015,118,13,50,241.476,31,1,1,0,0,False,False,False,False
56,16/09/2015,225,26,28,241.476,24,1,1,2,3,False,False,True,False
57,23/09/2015,179,51,38,241.476,31,1,0,0,3,False,False,False,True
58,30/09/2015,369,17,31,241.476,25,1,3,0,0,False,False,False,False
59,11/09/2015,248,25,47,241.476,32,1,2,1,1,False,False,False,True
60,18/09/2015,179,51,38,241.476,31,1,0,0,3,False,False,False,True
61,25/09/2015,260,50,36,241.476,23,1,4,0,4,False,False,False,True
62,06/10/2015,179,51,38,253.465,31,1,0,0,3,False,False,False,True
63,13/10/2015,118,10,37,253.465,28,1,0,0,3,False,False,False,True
64,14/10/2015,118,13,50,253.465,31,1,1,0,0,False,False,False,False
65,15/10/2015,179,26,30,253.465,19,3,0,0,1,False,False,False,True
66,16/10/2015,179,51,38,253.465,31,1,0,0,3,False,False,False,True
67,16/10/2015,225,26,28,253.465,24,1,1,2,3,False,False,False,True
68,06/10/2015,118,10,37,253.465,28,1,0,0,3,False,False,False,True
69,14/10/2015,225,26,28,253.465,24,1,1,2,2,False,False,False,True
70,21/10/2015,248,25,47,253.465,32,1,2,1,2,False,False,False,True
71,22/10/2015,291,31,40,253.465,25,1,1,1,5,False,False,False,True
72,21/10/2015,179,51,38,253.465,31,1,0,0,8,False,False,False,True
73,21/10/2015,225,26,28,253.465,24,1,1,2,3,False,False,False,True
74,22/10/2015,260,50,36,253.465,23,1,4,0,16,False,False,True,False
75,13/10/2015,291,31,40,253.465,25,1,1,1,8,True,False,False,False
76,20/10/2015,225,26,28,253.465,24,1,1,2,2,False,False,False,True
77,21/10/2015,289,36,33,253.465,30,1,2,1,8,False,False,False,True
78,23/10/2015,361,52,28,253.465,27,1,1,4,1,False,False,False,True
79,30/10/2015,260,50,36,253.465,23,1,4,0,3,False,False,False,True
80,05/11/2015,179,51,38,306.345,31,1,0,0,1,False,False,False,True
81,04/11/2015,225,26,28,306.345,24,1,1,2,1,False,False,False,True
82,05/11/2015,179,51,38,306.345,31,1,0,0,8,True,False,False,False
83,12/11/2015,179,22,40,306.345,22,2,2,0,8,False,False,True,False
84,19/11/2015,291,31,40,306.345,25,1,1,1,5,False,False,False,True
85,02/11/2015,155,12,34,306.345,25,1,2,0,32,True,False,False,False
86,09/11/2015,189,29,33,306.345,25,1,2,2,8,False,False,False,True
87,16/11/2015,291,31,40,306.345,25,1,1,1,40,True,False,False,False
88,18/11/2015,225,26,28,306.345,24,1,1,2,1,False,False,False,True
89,20/11/2015,155,12,34,306.345,25,1,2,0,8,True,False,False,False
90,18/11/2015,225,26,28,306.345,24,1,1,2,3,False,False,False,True
91,25/11/2015,179,22,40,306.345,22,2,2,0,8,False,False,True,False
92,20/11/2015,225,26,28,306.345,24,1,1,2,3,True,False,False,False
93,27/11/2015,260,50,36,306.345,23,1,4,0,4,False,False,False,True
94,02/11/2015,248,25,47,306.345,32,1,2,1,1,False,False,False,True
95,10/11/2015,225,26,28,306.345,24,1,1,2,3,False,False,False,True
96,11/11/2015,289,36,33,306.345,30,1,2,1,24,True,False,False,False
97,26/11/2015,291,31,40,306.345,25,1,1,1,3,False,False,False,True
98,01/12/2015,248,25,47,261.306,32,1,2,1,1,False,False,False,True
99,01/12/2015,118,10,37,261.306,28,1,0,0,64,False,False,True,False
100,02/12/2015,118,13,50,261.306,31,1,1,0,2,False,False,False,True
101,02/12/2015,235,11,37,261.306,29,3,1,1,8,False,False,False,True
102,03/12/2015,225,26,28,261.306,24,1,1,2,2,False,False,False,True
103,04/12/2015,260,50,36,261.306,23,1,4,0,8,False,False,False,True
104,08/12/2015,118,10,37,261.306,28,1,0,0,56,False,False,True,False
105,09/12/2015,361,52,28,261.306,27,1,1,4,8,False,False,False,True
106,10/12/2015,225,26,28,261.306,24,1,1,2,3,False,False,False,True
107,11/12/2015,260,50,36,261.306,23,1,4,0,3,False,False,False,True
108,15/12/2015,225,26,28,261.306,24,1,1,2,2,False,False,False,True
109,16/12/2015,361,52,28,261.306,27,1,1,4,8,False,False,False,True
110,11/12/2015,118,10,37,261.306,28,1,0,0,2,False,False,False,True
111,18/12/2015,246,25,41,261.306,23,1,0,0,8,False,False,True,False
112,18/12/2015,225,26,28,261.306,24,1,1,2,2,False,False,False,True
113,06/01/2016,225,26,28,308.593,24,1,1,2,1,False,False,False,True
114,04/01/2016,118,10,37,308.593,28,1,0,0,1,False,False,True,False
115,05/01/2016,118,10,37,308.593,28,1,0,0,1,False,False,False,True
116,05/01/2016,155,12,34,308.593,25,1,2,0,8,False,False,True,False
117,06/01/2016,225,26,28,308.593,24,1,1,2,2,False,False,False,True
118,07/01/2016,184,42,27,308.593,21,1,0,0,2,False,False,False,True
119,07/01/2016,225,26,28,308.593,24,1,1,2,2,False,False,False,True
120,08/01/2016,225,26,28,308.593,24,1,1,2,1,False,False,False,True
121,11/01/2016,118,10,37,308.593,28,1,0,0,2,False,False,False,True
122,12/01/2016,225,26,28,308.593,24,1,1,2,2,False,False,False,True
123,12/01/2016,118,10,37,308.593,28,1,0,0,2,False,False,False,True
124,13/01/2016,118,10,37,308.593,28,1,0,0,2,False,False,False,True
125,14/01/2016,118,10,37,308.593,28,1,0,0,2,False,False,False,True
126,15/01/2016,118,10,37,308.593,28,1,0,0,2,False,False,False,True
127,11/01/2016,118,10,37,308.593,28,1,0,0,2,False,False,False,True
128,12/01/2016,118,10,37,308.593,28,1,0,0,2,False,False,False,True
129,12/01/2016,179,26,30,308.593,19,3,0,0,8,False,False,True,False
130,12/01/2016,289,36,33,308.593,30,1,2,1,8,False,False,True,False
131,13/01/2016,118,10,37,308.593,28,1,0,0,2,False,False,False,True
132,21/01/2016,184,42,27,308.593,21,1,0,0,2,False,False,False,True
133,28/01/2016,118,10,37,308.593,28,1,0,0,2,False,False,False,True
134,25/01/2016,118,10,37,308.593,28,1,0,0,0,False,False,False,True
135,26/01/2016,225,26,28,308.593,24,1,1,2,1,False,False,False,True
136,28/01/2016,289,36,33,308.593,30,1,2,1,3,False,False,False,True
137,05/02/2016,184,42,27,302.585,21,1,0,0,1,False,False,False,True
138,03/02/2016,246,25,41,302.585,23,1,0,0,8,True,False,False,False
139,10/02/2016,179,51,38,302.585,31,1,0,0,8,True,False,False,False
140,11/02/2016,155,12,34,302.585,25,1,2,0,2,False,False,False,True
141,11/02/2016,189,29,33,302.585,25,1,2,2,8,False,False,False,True
142,12/02/2016,260,50,36,302.585,23,1,4,0,2,False,False,False,True
143,12/02/2016,289,36,33,302.585,30,1,2,1,8,False,False,False,True
144,08/02/2016,388,15,50,302.585,24,1,0,0,8,True,False,False,False
145,09/02/2016,388,15,50,302.585,24,1,0,0,8,True,False,False,False
146,15/02/2016,225,26,28,302.585,24,1,1,2,2,False,False,False,True
147,09/02/2016,225,26,28,302.585,24,1,1,2,2,False,False,False,True
148,16/02/2016,179,26,30,302.585,19,3,0,0,1,False,False,False,True
149,23/02/2016,184,42,27,302.585,21,1,0,0,8,False,False,False,True
150,25/02/2016,225,26,28,302.585,24,1,1,2,3,False,False,False,True
151,15/02/2016,330,16,28,302.585,25,2,0,0,8,False,False,True,False
152,16/02/2016,330,16,28,302.585,25,2,0,0,1,False,False,False,True
153,17/02/2016,225,26,28,302.585,24,1,1,2,1,False,False,False,True
154,25/02/2016,189,29,33,302.585,25,1,2,2,8,False,False,True,False
155,01/03/2016,291,50,32,343.253,23,1,0,0,2,False,False,False,True
156,01/03/2016,260,50,36,343.253,23,1,4,0,8,False,False,True,False
157,08/03/2016,157,27,29,343.253,22,1,0,0,3,False,False,True,False
158,15/03/2016,179,22,40,343.253,22,2,2,0,8,False,True,False,False
159,16/03/2016,291,31,40,343.253,25,1,1,1,8,False,False,False,True
160,02/03/2016,260,50,36,343.253,23,1,4,0,8,True,False,False,False
161,03/03/2016,179,26,30,343.253,19,3,0,0,8,True,False,False,False
162,04/03/2016,248,25,47,343.253,32,1,2,1,3,True,False,False,False
163,04/03/2016,260,50,36,343.253,23,1,4,0,40,True,False,False,False
164,07/03/2016,179,22,40,343.253,22,2,2,0,40,True,False,False,False
165,14/03/2016,155,12,34,343.253,25,1,2,0,16,True,False,False,False
166,21/03/2016,260,50,36,343.253,23,1,4,0,16,False,False,False,True
167,22/03/2016,155,12,34,343.253,25,1,2,0,8,True,False,False,False
168,24/03/2016,289,36,33,343.253,30,1,2,1,8,True,False,False,False
169,24/03/2016,179,22,40,343.253,22,2,2,0,8,True,False,False,False
170,25/03/2016,260,50,36,343.253,23,1,4,0,4,False,False,False,True
171,25/03/2016,225,26,28,343.253,24,1,1,2,1,False,False,False,True
172,28/03/2016,279,5,39,343.253,24,1,2,0,8,True,False,False,False
173,29/03/2016,179,51,38,343.253,31,1,0,0,24,True,False,False,False
174,30/03/2016,225,26,28,343.253,24,1,1,2,2,False,False,False,True
175,28/03/2016,225,26,28,343.253,24,1,1,2,8,True,False,False,False
176,28/03/2016,179,26,30,343.253,19,3,0,0,1,True,False,False,False
177,29/03/2016,225,26,28,343.253,24,1,1,2,8,True,False,False,False
178,30/03/2016,225,26,28,343.253,24,1,1,2,16,True,False,False,False
179,30/03/2016,179,51,38,343.253,31,1,0,0,3,True,False,False,False
180,17/03/2016,279,5,39,343.253,24,1,2,0,16,True,False,False,False
181,18/03/2016,225,26,28,343.253,24,1,1,2,2,False,False,False,True
182,25/03/2016,248,25,47,343.253,32,1,2,1,3,True,False,False,False
183,28/03/2016,225,26,28,343.253,24,1,1,2,1,False,False,False,True
184,06/04/2016,291,31,40,326.452,25,1,1,1,1,False,False,False,True
185,13/04/2016,225,26,28,326.452,24,1,1,2,1,False,False,False,True
186,12/04/2016,155,12,34,326.452,25,1,2,0,1,False,False,False,True
187,13/04/2016,246,25,41,326.452,23,1,0,0,24,True,False,False,False
188,14/04/2016,155,12,34,326.452,25,1,2,0,1,False,False,False,True
189,15/04/2016,225,26,28,326.452,24,1,1,2,2,False,False,False,True
190,15/04/2016,260,50,36,326.452,23,1,4,0,4,False,False,False,True
191,06/04/2016,179,51,38,326.452,31,1,0,0,24,True,False,False,False
192,07/04/2016,118,13,50,326.452,31,1,1,0,1,False,False,False,True
193,08/04/2016,291,31,40,326.452,25,1,1,1,3,False,False,False,True
194,08/04/2016,246,25,41,326.452,23,1,0,0,8,True,False,False,False
195,22/04/2016,291,31,40,326.452,25,1,1,1,1,False,False,False,True
196,29/04/2016,248,25,47,326.452,32,1,2,1,8,False,False,False,True
197,29/04/2016,260,50,36,326.452,23,1,4,0,56,False,False,True,False
198,26/04/2016,289,36,33,326.452,30,1,2,1,8,False,False,True,False
199,27/04/2016,155,12,34,326.452,25,1,2,0,24,True,False,False,False
200,27/04/2016,378,49,36,326.452,21,1,2,4,8,False,False,True,False
201,28/04/2016,289,36,33,326.452,30,1,2,1,16,True,False,False,False
202,08/04/2016,235,11,37,326.452,29,3,1,1,3,True,False,False,False
203,04/04/2016,235,29,48,326.452,33,1,1,5,0,False,False,False,False
204,04/05/2016,289,36,33,378.884,30,1,2,1,8,True,False,False,False
205,05/05/2016,155,12,34,378.884,25,1,2,0,2,False,False,False,True
206,02/05/2016,155,12,34,378.884,25,1,2,0,1,False,False,False,True
207,03/05/2016,179,51,38,378.884,31,1,0,0,8,False,False,True,False
208,03/05/2016,225,26,28,378.884,24,1,1,2,8,False,False,True,False
209,11/05/2016,184,42,27,378.884,21,1,0,0,4,True,False,False,False
210,09/05/2016,155,12,34,378.884,25,1,2,0,2,False,False,False,True
211,10/05/2016,179,51,38,378.884,31,1,0,0,1,True,False,False,False
212,04/05/2016,289,36,33,378.884,30,1,2,1,24,True,False,False,False
213,11/05/2016,279,5,39,378.884,24,1,2,0,0,False,False,False,False
214,18/05/2016,330,16,28,378.884,25,2,0,0,0,False,False,False,False
215,25/05/2016,378,49,36,378.884,21,1,2,4,0,False,False,False,False
216,25/05/2016,388,15,50,378.884,24,1,0,0,0,False,False,False,False
217,24/05/2016,179,51,38,378.884,31,1,0,0,1,True,False,False,False
218,11/05/2016,118,13,50,378.884,31,1,1,0,24,True,False,False,False
219,27/05/2016,361,52,28,378.884,27,1,1,4,8,False,False,False,True
220,06/06/2016,246,25,41,377.550,23,1,0,0,8,False,False,True,False
221,13/06/2016,361,52,28,377.550,27,1,1,4,8,False,False,False,True
222,14/06/2016,246,25,41,377.550,23,1,0,0,24,True,False,False,False
223,16/06/2016,291,31,40,377.550,25,1,1,1,4,False,False,False,True
224,17/06/2016,246,25,41,377.550,23,1,0,0,8,True,False,False,False
225,13/06/2016,179,51,38,377.550,31,1,0,0,8,True,False,False,False
226,20/06/2016,155,12,34,377.550,25,1,2,0,4,False,False,False,True
227,27/06/2016,246,25,41,377.550,23,1,0,0,8,True,False,False,False
228,29/06/2016,118,13,50,377.550,31,1,1,0,8,True,False,False,False
229,03/06/2016,235,11,37,377.550,29,3,1,1,16,True,False,False,False
230,07/06/2016,118,13,50,377.550,31,1,1,0,1,False,False,False,True
231,08/06/2016,118,13,50,377.550,31,1,1,0,80,True,False,False,False
232,09/06/2016,378,49,36,377.550,21,1,2,4,8,False,False,False,True
233,10/06/2016,179,51,38,377.550,31,1,0,0,2,True,False,False,False
234,20/06/2016,289,48,49,377.550,36,1,0,2,2,False,False,False,True
235,30/06/2016,225,26,28,377.550,24,1,1,2,2,False,False,False,True
236,05/07/2016,155,12,34,275.312,25,1,2,0,16,False,False,True,False
237,06/07/2016,118,13,50,275.312,31,1,1,0,8,True,False,False,False
238,08/07/2016,118,10,37,275.312,28,1,0,0,8,True,False,False,False
239,08/07/2016,118,10,37,275.312,28,1,0,0,4,False,False,False,True
240,12/07/2016,330,16,28,275.312,25,2,0,0,8,False,False,False,True
241,14/07/2016,179,26,30,275.312,19,3,0,0,8,False,False,True,False
242,15/07/2016,155,12,34,275.312,25,1,2,0,2,False,False,False,True
243,18/07/2016,330,16,28,275.312,25,2,0,0,8,True,False,False,False
244,19/07/2016,330,16,28,275.312,25,2,0,0,8,True,False,False,False
245,18/07/2016,157,27,29,275.312,22,1,0,0,3,False,False,False,True
246,19/07/2016,361,52,28,275.312,27,1,1,4,8,False,False,False,True
247,20/07/2016,289,36,33,275.312,30,1,2,1,8,False,False,False,True
248,21/07/2016,179,51,38,275.312,31,1,0,0,8,False,False,False,True
249,11/07/2016,289,36,33,275.312,30,1,2,1,32,False,False,True,False
250,14/07/2016,289,36,33,275.312,30,1,2,1,8,False,False,True,False
251,21/07/2016,260,50,36,275.312,23,1,4,0,0,False,False,False,False
252,04/08/2016,289,36,33,265.615,30,1,2,1,8,False,False,True,False
253,11/08/2016,157,27,29,265.615,22,1,0,0,3,False,False,True,False
254,07/08/2016,289,36,33,265.615,30,1,2,1,1,False,False,False,True
255,08/08/2016,228,14,58,265.615,22,1,2,1,8,False,False,True,False
256,10/08/2016,300,26,43,265.615,25,1,2,1,1,True,False,False,False
257,10/08/2016,300,26,43,265.615,25,1,2,1,2,True,False,False,False
258,11/08/2016,260,50,36,265.615,23,1,4,0,4,False,False,False,True
259,08/08/2016,289,36,33,265.615,30,1,2,1,4,False,False,False,True
260,09/08/2016,248,25,47,265.615,32,1,2,1,1,False,False,False,True
261,10/08/2016,268,11,33,265.615,25,2,0,0,8,True,False,False,False
262,10/08/2016,179,26,30,265.615,19,3,0,0,1,False,False,False,True
263,10/08/2016,118,13,50,265.615,31,1,1,0,3,True,False,False,False
264,14/08/2016,248,25,47,265.615,32,1,2,1,2,False,False,False,True
265,15/08/2016,235,11,37,265.615,29,3,1,1,1,False,False,False,True
266,17/08/2016,118,13,50,265.615,31,1,1,0,1,False,False,False,True
267,24/08/2016,235,11,37,265.615,29,3,1,1,8,False,False,True,False
268,08/08/2016,361,52,28,265.615,27,1,1,4,8,True,False,False,False
269,30/08/2016,184,42,27,265.615,21,1,0,0,8,True,False,False,False
270,05/09/2016,179,51,38,294.217,31,1,0,0,8,True,False,False,False
271,09/09/2016,179,51,38,294.217,31,1,0,0,3,False,False,False,True
272,07/09/2016,289,36,33,294.217,30,1,2,1,24,False,False,True,False
273,08/09/2016,235,20,43,294.217,38,1,1,0,0,False,False,False,False
274,12/09/2016,246,25,41,294.217,23,1,0,0,16,True,False,False,False
275,13/09/2016,291,31,40,294.217,25,1,1,1,3,False,False,False,True
276,13/09/2016,231,35,39,294.217,35,1,2,2,0,False,False,False,False
277,13/09/2016,291,50,32,294.217,23,1,0,0,0,False,False,False,False
278,14/09/2016,179,51,38,294.217,31,1,0,0,8,True,False,False,False
279,14/09/2016,246,25,41,294.217,23,1,0,0,32,True,False,False,False
280,15/09/2016,179,51,38,294.217,31,1,0,0,1,False,False,False,True
281,16/09/2016,291,31,40,294.217,25,1,1,1,4,False,False,False,True
282,16/09/2016,260,50,36,294.217,23,1,4,0,4,False,False,False,True
283,14/09/2016,235,20,43,294.217,38,1,1,0,8,False,False,False,True
284,15/09/2016,118,13,50,294.217,31,1,1,0,1,False,False,False,True
285,15/09/2016,235,20,43,294.217,38,1,1,0,0,False,False,False,False
286,16/09/2016,291,31,40,294.217,25,1,1,1,3,False,False,False,True
287,26/09/2016,291,31,40,294.217,25,1,1,1,40,True,False,False,False
288,26/09/2016,179,51,38,294.217,31,1,0,0,8,True,False,False,False
289,05/10/2016,289,36,33,265.017,30,1,2,1,8,False,False,False,True
290,05/10/2016,235,11,37,265.017,29,3,1,1,4,False,False,False,True
291,05/10/2016,289,36,33,265.017,30,1,2,1,8,False,False,False,True
292,06/10/2016,289,36,33,265.017,30,1,2,1,8,False,False,False,True
293,06/10/2016,118,13,50,265.017,31,1,1,0,0,False,False,False,False
294,06/10/2016,248,25,47,265.017,32,1,2,1,0,False,False,False,False
295,12/10/2016,179,26,30,265.017,19,3,0,0,8,True,False,False,False
296,12/10/2016,118,10,37,265.017,28,1,0,0,3,True,False,False,False

In [96]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [97]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

In [98]:
df.columns = column_names

In [99]:
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Reason_1,Reason_2,Reason_3,Reason_4
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,False,False,False,True
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,False,False,False,False
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,False,False,False,True
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,True,False,False,False
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,False,False,False,True

In [100]:
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [101]:
df = df[column_names_reordered]

In [102]:
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [103]:
df_checkpoint = df.copy()
df_checkpoint

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,False,False,False,True,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,False,False,False,True,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,False,False,False,True,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,False,False,True,False,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,False,False,False,True,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,True,False,False,False,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,True,False,False,False,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,True,False,False,False,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,True,False,False,False,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,True,False,False,False,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,False,False,False,True,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,False,False,True,False,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,True,False,False,False,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,False,False,False,True,05/08/2015,248,25,47,205.917,32,1,2,1,2
20,True,False,False,False,12/08/2015,330,16,28,205.917,25,2,0,0,8
21,True,False,False,False,03/08/2015,179,51,38,205.917,31,1,0,0,1
22,True,False,False,False,10/08/2015,361,52,28,205.917,27,1,1,4,40
23,False,False,False,True,14/08/2015,260,50,36,205.917,23,1,4,0,4
24,False,False,True,False,17/08/2015,289,36,33,205.917,30,1,2,1,8
25,False,False,False,True,24/08/2015,361,52,28,205.917,27,1,1,4,7
26,False,False,False,True,04/08/2015,289,36,33,205.917,30,1,2,1,1
27,False,False,False,True,12/08/2015,157,27,29,205.917,22,1,0,0,4
28,False,False,True,False,19/08/2015,289,36,33,205.917,30,1,2,1,8
29,False,False,False,True,28/08/2015,179,51,38,205.917,31,1,0,0,2
30,False,False,True,False,17/08/2015,179,51,38,205.917,31,1,0,0,8
31,False,False,True,False,27/08/2015,235,29,48,205.917,33,1,1,5,8
32,False,False,False,True,27/08/2015,235,11,37,205.917,29,3,1,1,4
33,False,False,True,False,17/08/2015,235,29,48,205.917,33,1,1,5,8
34,False,False,False,True,17/08/2015,179,51,38,205.917,31,1,0,0,2
35,False,False,False,True,17/08/2015,361,52,28,205.917,27,1,1,4,1
36,False,False,False,True,04/08/2015,289,36,33,205.917,30,1,2,1,8
37,True,False,False,False,20/08/2015,291,50,32,205.917,23,1,0,0,4
38,False,False,False,True,21/08/2015,235,29,48,205.917,33,1,1,5,8
39,False,False,False,True,28/08/2015,260,50,36,205.917,23,1,4,0,4
40,False,False,False,True,01/09/2015,184,42,27,241.476,21,1,0,0,2
41,False,False,False,True,07/09/2015,118,10,37,241.476,28,1,0,0,4
42,False,False,False,True,01/09/2015,179,51,38,241.476,31,1,0,0,4
43,False,False,True,False,08/09/2015,235,20,43,241.476,38,1,1,0,8
44,False,False,False,True,09/09/2015,155,12,34,241.476,25,1,2,0,2
45,False,False,False,True,13/09/2015,118,10,37,241.476,28,1,0,0,3
46,False,False,False,True,14/09/2015,179,51,38,241.476,31,1,0,0,3
47,False,False,False,True,24/09/2015,291,31,40,241.476,25,1,1,1,4
48,False,False,False,True,04/09/2015,260,50,36,241.476,23,1,4,0,8
49,True,False,False,False,14/09/2015,291,31,40,241.476,25,1,1,1,32
50,False,False,False,False,21/09/2015,260,50,36,241.476,23,1,4,0,0
51,False,False,False,False,28/09/2015,225,26,28,241.476,24,1,1,2,0
52,False,False,False,True,08/09/2015,225,26,28,241.476,24,1,1,2,2
53,False,False,False,True,15/09/2015,118,10,37,241.476,28,1,0,0,2
54,False,False,False,False,22/09/2015,289,36,33,241.476,30,1,2,1,0
55,False,False,False,False,29/09/2015,118,13,50,241.476,31,1,1,0,0
56,False,False,True,False,16/09/2015,225,26,28,241.476,24,1,1,2,3
57,False,False,False,True,23/09/2015,179,51,38,241.476,31,1,0,0,3
58,False,False,False,False,30/09/2015,369,17,31,241.476,25,1,3,0,0
59,False,False,False,True,11/09/2015,248,25,47,241.476,32,1,2,1,1
60,False,False,False,True,18/09/2015,179,51,38,241.476,31,1,0,0,3
61,False,False,False,True,25/09/2015,260,50,36,241.476,23,1,4,0,4
62,False,False,False,True,06/10/2015,179,51,38,253.465,31,1,0,0,3
63,False,False,False,True,13/10/2015,118,10,37,253.465,28,1,0,0,3
64,False,False,False,False,14/10/2015,118,13,50,253.465,31,1,1,0,0
65,False,False,False,True,15/10/2015,179,26,30,253.465,19,3,0,0,1
66,False,False,False,True,16/10/2015,179,51,38,253.465,31,1,0,0,3
67,False,False,False,True,16/10/2015,225,26,28,253.465,24,1,1,2,3
68,False,False,False,True,06/10/2015,118,10,37,253.465,28,1,0,0,3
69,False,False,False,True,14/10/2015,225,26,28,253.465,24,1,1,2,2
70,False,False,False,True,21/10/2015,248,25,47,253.465,32,1,2,1,2
71,False,False,False,True,22/10/2015,291,31,40,253.465,25,1,1,1,5
72,False,False,False,True,21/10/2015,179,51,38,253.465,31,1,0,0,8
73,False,False,False,True,21/10/2015,225,26,28,253.465,24,1,1,2,3
74,False,False,True,False,22/10/2015,260,50,36,253.465,23,1,4,0,16
75,True,False,False,False,13/10/2015,291,31,40,253.465,25,1,1,1,8
76,False,False,False,True,20/10/2015,225,26,28,253.465,24,1,1,2,2
77,False,False,False,True,21/10/2015,289,36,33,253.465,30,1,2,1,8
78,False,False,False,True,23/10/2015,361,52,28,253.465,27,1,1,4,1
79,False,False,False,True,30/10/2015,260,50,36,253.465,23,1,4,0,3
80,False,False,False,True,05/11/2015,179,51,38,306.345,31,1,0,0,1
81,False,False,False,True,04/11/2015,225,26,28,306.345,24,1,1,2,1
82,True,False,False,False,05/11/2015,179,51,38,306.345,31,1,0,0,8
83,False,False,True,False,12/11/2015,179,22,40,306.345,22,2,2,0,8
84,False,False,False,True,19/11/2015,291,31,40,306.345,25,1,1,1,5
85,True,False,False,False,02/11/2015,155,12,34,306.345,25,1,2,0,32
86,False,False,False,True,09/11/2015,189,29,33,306.345,25,1,2,2,8
87,True,False,False,False,16/11/2015,291,31,40,306.345,25,1,1,1,40
88,False,False,False,True,18/11/2015,225,26,28,306.345,24,1,1,2,1
89,True,False,False,False,20/11/2015,155,12,34,306.345,25,1,2,0,8
90,False,False,False,True,18/11/2015,225,26,28,306.345,24,1,1,2,3
91,False,False,True,False,25/11/2015,179,22,40,306.345,22,2,2,0,8
92,True,False,False,False,20/11/2015,225,26,28,306.345,24,1,1,2,3
93,False,False,False,True,27/11/2015,260,50,36,306.345,23,1,4,0,4
94,False,False,False,True,02/11/2015,248,25,47,306.345,32,1,2,1,1
95,False,False,False,True,10/11/2015,225,26,28,306.345,24,1,1,2,3
96,True,False,False,False,11/11/2015,289,36,33,306.345,30,1,2,1,24
97,False,False,False,True,26/11/2015,291,31,40,306.345,25,1,1,1,3
98,False,False,False,True,01/12/2015,248,25,47,261.306,32,1,2,1,1
99,False,False,True,False,01/12/2015,118,10,37,261.306,28,1,0,0,64
100,False,False,False,True,02/12/2015,118,13,50,261.306,31,1,1,0,2
101,False,False,False,True,02/12/2015,235,11,37,261.306,29,3,1,1,8
102,False,False,False,True,03/12/2015,225,26,28,261.306,24,1,1,2,2
103,False,False,False,True,04/12/2015,260,50,36,261.306,23,1,4,0,8
104,False,False,True,False,08/12/2015,118,10,37,261.306,28,1,0,0,56
105,False,False,False,True,09/12/2015,361,52,28,261.306,27,1,1,4,8
106,False,False,False,True,10/12/2015,225,26,28,261.306,24,1,1,2,3
107,False,False,False,True,11/12/2015,260,50,36,261.306,23,1,4,0,3
108,False,False,False,True,15/12/2015,225,26,28,261.306,24,1,1,2,2
109,False,False,False,True,16/12/2015,361,52,28,261.306,27,1,1,4,8
110,False,False,False,True,11/12/2015,118,10,37,261.306,28,1,0,0,2
111,False,False,True,False,18/12/2015,246,25,41,261.306,23,1,0,0,8
112,False,False,False,True,18/12/2015,225,26,28,261.306,24,1,1,2,2
113,False,False,False,True,06/01/2016,225,26,28,308.593,24,1,1,2,1
114,False,False,True,False,04/01/2016,118,10,37,308.593,28,1,0,0,1
115,False,False,False,True,05/01/2016,118,10,37,308.593,28,1,0,0,1
116,False,False,True,False,05/01/2016,155,12,34,308.593,25,1,2,0,8
117,False,False,False,True,06/01/2016,225,26,28,308.593,24,1,1,2,2
118,False,False,False,True,07/01/2016,184,42,27,308.593,21,1,0,0,2
119,False,False,False,True,07/01/2016,225,26,28,308.593,24,1,1,2,2
120,False,False,False,True,08/01/2016,225,26,28,308.593,24,1,1,2,1
121,False,False,False,True,11/01/2016,118,10,37,308.593,28,1,0,0,2
122,False,False,False,True,12/01/2016,225,26,28,308.593,24,1,1,2,2
123,False,False,False,True,12/01/2016,118,10,37,308.593,28,1,0,0,2
124,False,False,False,True,13/01/2016,118,10,37,308.593,28,1,0,0,2
125,False,False,False,True,14/01/2016,118,10,37,308.593,28,1,0,0,2
126,False,False,False,True,15/01/2016,118,10,37,308.593,28,1,0,0,2
127,False,False,False,True,11/01/2016,118,10,37,308.593,28,1,0,0,2
128,False,False,False,True,12/01/2016,118,10,37,308.593,28,1,0,0,2
129,False,False,True,False,12/01/2016,179,26,30,308.593,19,3,0,0,8
130,False,False,True,False,12/01/2016,289,36,33,308.593,30,1,2,1,8
131,False,False,False,True,13/01/2016,118,10,37,308.593,28,1,0,0,2
132,False,False,False,True,21/01/2016,184,42,27,308.593,21,1,0,0,2
133,False,False,False,True,28/01/2016,118,10,37,308.593,28,1,0,0,2
134,False,False,False,True,25/01/2016,118,10,37,308.593,28,1,0,0,0
135,False,False,False,True,26/01/2016,225,26,28,308.593,24,1,1,2,1
136,False,False,False,True,28/01/2016,289,36,33,308.593,30,1,2,1,3
137,False,False,False,True,05/02/2016,184,42,27,302.585,21,1,0,0,1
138,True,False,False,False,03/02/2016,246,25,41,302.585,23,1,0,0,8
139,True,False,False,False,10/02/2016,179,51,38,302.585,31,1,0,0,8
140,False,False,False,True,11/02/2016,155,12,34,302.585,25,1,2,0,2
141,False,False,False,True,11/02/2016,189,29,33,302.585,25,1,2,2,8
142,False,False,False,True,12/02/2016,260,50,36,302.585,23,1,4,0,2
143,False,False,False,True,12/02/2016,289,36,33,302.585,30,1,2,1,8
144,True,False,False,False,08/02/2016,388,15,50,302.585,24,1,0,0,8
145,True,False,False,False,09/02/2016,388,15,50,302.585,24,1,0,0,8
146,False,False,False,True,15/02/2016,225,26,28,302.585,24,1,1,2,2
147,False,False,False,True,09/02/2016,225,26,28,302.585,24,1,1,2,2
148,False,False,False,True,16/02/2016,179,26,30,302.585,19,3,0,0,1
149,False,False,False,True,23/02/2016,184,42,27,302.585,21,1,0,0,8
150,False,False,False,True,25/02/2016,225,26,28,302.585,24,1,1,2,3
151,False,False,True,False,15/02/2016,330,16,28,302.585,25,2,0,0,8
152,False,False,False,True,16/02/2016,330,16,28,302.585,25,2,0,0,1
153,False,False,False,True,17/02/2016,225,26,28,302.585,24,1,1,2,1
154,False,False,True,False,25/02/2016,189,29,33,302.585,25,1,2,2,8
155,False,False,False,True,01/03/2016,291,50,32,343.253,23,1,0,0,2
156,False,False,True,False,01/03/2016,260,50,36,343.253,23,1,4,0,8
157,False,False,True,False,08/03/2016,157,27,29,343.253,22,1,0,0,3
158,False,True,False,False,15/03/2016,179,22,40,343.253,22,2,2,0,8
159,False,False,False,True,16/03/2016,291,31,40,343.253,25,1,1,1,8
160,True,False,False,False,02/03/2016,260,50,36,343.253,23,1,4,0,8
161,True,False,False,False,03/03/2016,179,26,30,343.253,19,3,0,0,8
162,True,False,False,False,04/03/2016,248,25,47,343.253,32,1,2,1,3
163,True,False,False,False,04/03/2016,260,50,36,343.253,23,1,4,0,40
164,True,False,False,False,07/03/2016,179,22,40,343.253,22,2,2,0,40
165,True,False,False,False,14/03/2016,155,12,34,343.253,25,1,2,0,16
166,False,False,False,True,21/03/2016,260,50,36,343.253,23,1,4,0,16
167,True,False,False,False,22/03/2016,155,12,34,343.253,25,1,2,0,8
168,True,False,False,False,24/03/2016,289,36,33,343.253,30,1,2,1,8
169,True,False,False,False,24/03/2016,179,22,40,343.253,22,2,2,0,8
170,False,False,False,True,25/03/2016,260,50,36,343.253,23,1,4,0,4
171,False,False,False,True,25/03/2016,225,26,28,343.253,24,1,1,2,1
172,True,False,False,False,28/03/2016,279,5,39,343.253,24,1,2,0,8
173,True,False,False,False,29/03/2016,179,51,38,343.253,31,1,0,0,24
174,False,False,False,True,30/03/2016,225,26,28,343.253,24,1,1,2,2
175,True,False,False,False,28/03/2016,225,26,28,343.253,24,1,1,2,8
176,True,False,False,False,28/03/2016,179,26,30,343.253,19,3,0,0,1
177,True,False,False,False,29/03/2016,225,26,28,343.253,24,1,1,2,8
178,True,False,False,False,30/03/2016,225,26,28,343.253,24,1,1,2,16
179,True,False,False,False,30/03/2016,179,51,38,343.253,31,1,0,0,3
180,True,False,False,False,17/03/2016,279,5,39,343.253,24,1,2,0,16
181,False,False,False,True,18/03/2016,225,26,28,343.253,24,1,1,2,2
182,True,False,False,False,25/03/2016,248,25,47,343.253,32,1,2,1,3
183,False,False,False,True,28/03/2016,225,26,28,343.253,24,1,1,2,1
184,False,False,False,True,06/04/2016,291,31,40,326.452,25,1,1,1,1
185,False,False,False,True,13/04/2016,225,26,28,326.452,24,1,1,2,1
186,False,False,False,True,12/04/2016,155,12,34,326.452,25,1,2,0,1
187,True,False,False,False,13/04/2016,246,25,41,326.452,23,1,0,0,24
188,False,False,False,True,14/04/2016,155,12,34,326.452,25,1,2,0,1
189,False,False,False,True,15/04/2016,225,26,28,326.452,24,1,1,2,2
190,False,False,False,True,15/04/2016,260,50,36,326.452,23,1,4,0,4
191,True,False,False,False,06/04/2016,179,51,38,326.452,31,1,0,0,24
192,False,False,False,True,07/04/2016,118,13,50,326.452,31,1,1,0,1
193,False,False,False,True,08/04/2016,291,31,40,326.452,25,1,1,1,3
194,True,False,False,False,08/04/2016,246,25,41,326.452,23,1,0,0,8
195,False,False,False,True,22/04/2016,291,31,40,326.452,25,1,1,1,1
196,False,False,False,True,29/04/2016,248,25,47,326.452,32,1,2,1,8
197,False,False,True,False,29/04/2016,260,50,36,326.452,23,1,4,0,56
198,False,False,True,False,26/04/2016,289,36,33,326.452,30,1,2,1,8
199,True,False,False,False,27/04/2016,155,12,34,326.452,25,1,2,0,24
200,False,False,True,False,27/04/2016,378,49,36,326.452,21,1,2,4,8
201,True,False,False,False,28/04/2016,289,36,33,326.452,30,1,2,1,16
202,True,False,False,False,08/04/2016,235,11,37,326.452,29,3,1,1,3
203,False,False,False,False,04/04/2016,235,29,48,326.452,33,1,1,5,0
204,True,False,False,False,04/05/2016,289,36,33,378.884,30,1,2,1,8
205,False,False,False,True,05/05/2016,155,12,34,378.884,25,1,2,0,2
206,False,False,False,True,02/05/2016,155,12,34,378.884,25,1,2,0,1
207,False,False,True,False,03/05/2016,179,51,38,378.884,31,1,0,0,8
208,False,False,True,False,03/05/2016,225,26,28,378.884,24,1,1,2,8
209,True,False,False,False,11/05/2016,184,42,27,378.884,21,1,0,0,4
210,False,False,False,True,09/05/2016,155,12,34,378.884,25,1,2,0,2
211,True,False,False,False,10/05/2016,179,51,38,378.884,31,1,0,0,1
212,True,False,False,False,04/05/2016,289,36,33,378.884,30,1,2,1,24
213,False,False,False,False,11/05/2016,279,5,39,378.884,24,1,2,0,0
214,False,False,False,False,18/05/2016,330,16,28,378.884,25,2,0,0,0
215,False,False,False,False,25/05/2016,378,49,36,378.884,21,1,2,4,0
216,False,False,False,False,25/05/2016,388,15,50,378.884,24,1,0,0,0
217,True,False,False,False,24/05/2016,179,51,38,378.884,31,1,0,0,1
218,True,False,False,False,11/05/2016,118,13,50,378.884,31,1,1,0,24
219,False,False,False,True,27/05/2016,361,52,28,378.884,27,1,1,4,8
220,False,False,True,False,06/06/2016,246,25,41,377.550,23,1,0,0,8
221,False,False,False,True,13/06/2016,361,52,28,377.550,27,1,1,4,8
222,True,False,False,False,14/06/2016,246,25,41,377.550,23,1,0,0,24
223,False,False,False,True,16/06/2016,291,31,40,377.550,25,1,1,1,4
224,True,False,False,False,17/06/2016,246,25,41,377.550,23,1,0,0,8
225,True,False,False,False,13/06/2016,179,51,38,377.550,31,1,0,0,8
226,False,False,False,True,20/06/2016,155,12,34,377.550,25,1,2,0,4
227,True,False,False,False,27/06/2016,246,25,41,377.550,23,1,0,0,8
228,True,False,False,False,29/06/2016,118,13,50,377.550,31,1,1,0,8
229,True,False,False,False,03/06/2016,235,11,37,377.550,29,3,1,1,16
230,False,False,False,True,07/06/2016,118,13,50,377.550,31,1,1,0,1
231,True,False,False,False,08/06/2016,118,13,50,377.550,31,1,1,0,80
232,False,False,False,True,09/06/2016,378,49,36,377.550,21,1,2,4,8
233,True,False,False,False,10/06/2016,179,51,38,377.550,31,1,0,0,2
234,False,False,False,True,20/06/2016,289,48,49,377.550,36,1,0,2,2
235,False,False,False,True,30/06/2016,225,26,28,377.550,24,1,1,2,2
236,False,False,True,False,05/07/2016,155,12,34,275.312,25,1,2,0,16
237,True,False,False,False,06/07/2016,118,13,50,275.312,31,1,1,0,8
238,True,False,False,False,08/07/2016,118,10,37,275.312,28,1,0,0,8
239,False,False,False,True,08/07/2016,118,10,37,275.312,28,1,0,0,4
240,False,False,False,True,12/07/2016,330,16,28,275.312,25,2,0,0,8
241,False,False,True,False,14/07/2016,179,26,30,275.312,19,3,0,0,8
242,False,False,False,True,15/07/2016,155,12,34,275.312,25,1,2,0,2
243,True,False,False,False,18/07/2016,330,16,28,275.312,25,2,0,0,8
244,True,False,False,False,19/07/2016,330,16,28,275.312,25,2,0,0,8
245,False,False,False,True,18/07/2016,157,27,29,275.312,22,1,0,0,3
246,False,False,False,True,19/07/2016,361,52,28,275.312,27,1,1,4,8
247,False,False,False,True,20/07/2016,289,36,33,275.312,30,1,2,1,8
248,False,False,False,True,21/07/2016,179,51,38,275.312,31,1,0,0,8
249,False,False,True,False,11/07/2016,289,36,33,275.312,30,1,2,1,32
250,False,False,True,False,14/07/2016,289,36,33,275.312,30,1,2,1,8
251,False,False,False,False,21/07/2016,260,50,36,275.312,23,1,4,0,0
252,False,False,True,False,04/08/2016,289,36,33,265.615,30,1,2,1,8
253,False,False,True,False,11/08/2016,157,27,29,265.615,22,1,0,0,3
254,False,False,False,True,07/08/2016,289,36,33,265.615,30,1,2,1,1
255,False,False,True,False,08/08/2016,228,14,58,265.615,22,1,2,1,8
256,True,False,False,False,10/08/2016,300,26,43,265.615,25,1,2,1,1
257,True,False,False,False,10/08/2016,300,26,43,265.615,25,1,2,1,2
258,False,False,False,True,11/08/2016,260,50,36,265.615,23,1,4,0,4
259,False,False,False,True,08/08/2016,289,36,33,265.615,30,1,2,1,4
260,False,False,False,True,09/08/2016,248,25,47,265.615,32,1,2,1,1
261,True,False,False,False,10/08/2016,268,11,33,265.615,25,2,0,0,8
262,False,False,False,True,10/08/2016,179,26,30,265.615,19,3,0,0,1
263,True,False,False,False,10/08/2016,118,13,50,265.615,31,1,1,0,3
264,False,False,False,True,14/08/2016,248,25,47,265.615,32,1,2,1,2
265,False,False,False,True,15/08/2016,235,11,37,265.615,29,3,1,1,1
266,False,False,False,True,17/08/2016,118,13,50,265.615,31,1,1,0,1
267,False,False,True,False,24/08/2016,235,11,37,265.615,29,3,1,1,8
268,True,False,False,False,08/08/2016,361,52,28,265.615,27,1,1,4,8
269,True,False,False,False,30/08/2016,184,42,27,265.615,21,1,0,0,8
270,True,False,False,False,05/09/2016,179,51,38,294.217,31,1,0,0,8
271,False,False,False,True,09/09/2016,179,51,38,294.217,31,1,0,0,3
272,False,False,True,False,07/09/2016,289,36,33,294.217,30,1,2,1,24
273,False,False,False,False,08/09/2016,235,20,43,294.217,38,1,1,0,0
274,True,False,False,False,12/09/2016,246,25,41,294.217,23,1,0,0,16
275,False,False,False,True,13/09/2016,291,31,40,294.217,25,1,1,1,3
276,False,False,False,False,13/09/2016,231,35,39,294.217,35,1,2,2,0
277,False,False,False,False,13/09/2016,291,50,32,294.217,23,1,0,0,0
278,True,False,False,False,14/09/2016,179,51,38,294.217,31,1,0,0,8
279,True,False,False,False,14/09/2016,246,25,41,294.217,23,1,0,0,32
280,False,False,False,True,15/09/2016,179,51,38,294.217,31,1,0,0,1
281,False,False,False,True,16/09/2016,291,31,40,294.217,25,1,1,1,4
282,False,False,False,True,16/09/2016,260,50,36,294.217,23,1,4,0,4
283,False,False,False,True,14/09/2016,235,20,43,294.217,38,1,1,0,8
284,False,False,False,True,15/09/2016,118,13,50,294.217,31,1,1,0,1
285,False,False,False,False,15/09/2016,235,20,43,294.217,38,1,1,0,0
286,False,False,False,True,16/09/2016,291,31,40,294.217,25,1,1,1,3
287,True,False,False,False,26/09/2016,291,31,40,294.217,25,1,1,1,40
288,True,False,False,False,26/09/2016,179,51,38,294.217,31,1,0,0,8
289,False,False,False,True,05/10/2016,289,36,33,265.017,30,1,2,1,8
290,False,False,False,True,05/10/2016,235,11,37,265.017,29,3,1,1,4
291,False,False,False,True,05/10/2016,289,36,33,265.017,30,1,2,1,8
292,False,False,False,True,06/10/2016,289,36,33,265.017,30,1,2,1,8
293,False,False,False,False,06/10/2016,118,13,50,265.017,31,1,1,0,0
294,False,False,False,False,06/10/2016,248,25,47,265.017,32,1,2,1,0
295,True,False,False,False,12/10/2016,179,26,30,265.017,19,3,0,0,8

In [104]:
df_reason_mod = df_checkpoint

In [105]:
type(df_reason_mod['Date'][0])

str

In [106]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format='%d/%m/%Y')

In [107]:
type(df_reason_mod['Date'])

pandas.core.series.Series

In [108]:
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Reason_1                   700 non-null    bool
 1   Reason_2                   700 non-null    bool
 2   Reason_3                   700 non-null    bool
 3   Reason_4                   700 non-null    bool
 4   Date                       700 non-null    datetime64[ns]
 5   Transportation Expense     700 non-null    int64
 6   Distance to Work           700 non-null    int64
 7   Age                        700 non-null    int64
 8   Daily Work Load Average    700 non-null    float64
 9   Body Mass Index            700 non-null    int64
 10  Education                  700 non-null    int64
 11  Children                   700 non-null    int64
 12  Pets                       700 non-null    int64
 13  Absenteeism Time in Hours  700 non-null    int64
dtypes: bool(4), datetime64[ns](1), float64(1), int64(8)
memory usage: 57.6 KB

In [109]:
df_reason_mod['Date'][0]

Timestamp('2015-07-07 00:00:00')

In [110]:
df_reason_mod['Date'][0].month

7

In [111]:
list_months = []
list_months

[]

In [112]:
for i in range(df_reason_mod.shape[0]):
    list_months.append(df_reason_mod['Date'][i].month)

In [113]:
list_months

[7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5]

In [114]:
len(list_months)

700

In [115]:
df_reason_mod['Month of the Week'] = list_months

In [116]:
df_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month of the Week
0,False,False,False,True,2015-07-07,289,36,33,239.554,30,1,2,1,4,7
1,False,False,False,False,2015-07-14,118,13,50,239.554,31,1,1,0,0,7
2,False,False,False,True,2015-07-15,179,51,38,239.554,31,1,0,0,2,7
3,True,False,False,False,2015-07-16,279,5,39,239.554,24,1,2,0,4,7
4,False,False,False,True,2015-07-23,289,36,33,239.554,30,1,2,1,2,7

In [117]:
list_days = []
list_days

[]

In [118]:
for i in range(df_reason_mod.shape[0]):
    list_days.append(df_reason_mod['Date'][i].weekday())

In [119]:
df_reason_mod['Day of the Week'] = list_days

In [120]:
df_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month of the Week,Day of the Week
0,False,False,False,True,2015-07-07,289,36,33,239.554,30,1,2,1,4,7,1
1,False,False,False,False,2015-07-14,118,13,50,239.554,31,1,1,0,0,7,1
2,False,False,False,True,2015-07-15,179,51,38,239.554,31,1,0,0,2,7,2
3,True,False,False,False,2015-07-16,279,5,39,239.554,24,1,2,0,4,7,3
4,False,False,False,True,2015-07-23,289,36,33,239.554,30,1,2,1,2,7,3

In [121]:
df_reason_mod['Education'].unique()

array([1, 3, 2, 4])

In [122]:
df_reason_mod['Education'].value_counts()

Education
1    583
3     73
2     40
4      4
Name: count, dtype: int64

In [123]:
df_reason_mod['Education'] = df_reason_mod['Education'].map({1:0,2:1,3:1,4:1})

In [124]:
df_reason_mod['Education'].unique()

array([0, 1])

In [125]:
df_reason_mod['Education'].value_counts()

Education
0    583
1    117
Name: count, dtype: int64

In [126]:
df_reason_mod.head(20)

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month of the Week,Day of the Week
0,False,False,False,True,2015-07-07,289,36,33,239.554,30,0,2,1,4,7,1
1,False,False,False,False,2015-07-14,118,13,50,239.554,31,0,1,0,0,7,1
2,False,False,False,True,2015-07-15,179,51,38,239.554,31,0,0,0,2,7,2
3,True,False,False,False,2015-07-16,279,5,39,239.554,24,0,2,0,4,7,3
4,False,False,False,True,2015-07-23,289,36,33,239.554,30,0,2,1,2,7,3
5,False,False,False,True,2015-07-10,179,51,38,239.554,31,0,0,0,2,7,4
6,False,False,False,True,2015-07-17,361,52,28,239.554,27,0,1,4,8,7,4
7,False,False,False,True,2015-07-24,260,50,36,239.554,23,0,4,0,4,7,4
8,False,False,True,False,2015-07-06,155,12,34,239.554,25,0,2,0,40,7,0
9,False,False,False,True,2015-07-13,235,11,37,239.554,29,1,1,1,8,7,0
10,True,False,False,False,2015-07-20,260,50,36,239.554,23,0,4,0,8,7,0
11,True,False,False,False,2015-07-14,260,50,36,239.554,23,0,4,0,8,7,1
12,True,False,False,False,2015-07-15,260,50,36,239.554,23,0,4,0,8,7,2
13,True,False,False,False,2015-07-15,179,51,38,239.554,31,0,0,0,1,7,2
14,False,False,False,True,2015-07-15,179,51,38,239.554,31,0,0,0,4,7,2
15,True,False,False,False,2015-07-17,246,25,41,239.554,23,0,0,0,8,7,4
16,False,False,False,True,2015-07-17,179,51,38,239.554,31,0,0,0,2,7,4
17,False,False,True,False,2015-07-27,179,51,38,239.554,31,0,0,0,8,7,0
18,True,False,False,False,2015-07-30,189,29,33,239.554,25,0,2,2,8,7,3
19,False,False,False,True,2015-08-05,248,25,47,205.917,32,0,2,1,2,8,2

In [127]:
df_cleaned = df_reason_mod.copy()
df_cleaned.head(20)

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month of the Week,Day of the Week
0,False,False,False,True,2015-07-07,289,36,33,239.554,30,0,2,1,4,7,1
1,False,False,False,False,2015-07-14,118,13,50,239.554,31,0,1,0,0,7,1
2,False,False,False,True,2015-07-15,179,51,38,239.554,31,0,0,0,2,7,2
3,True,False,False,False,2015-07-16,279,5,39,239.554,24,0,2,0,4,7,3
4,False,False,False,True,2015-07-23,289,36,33,239.554,30,0,2,1,2,7,3
5,False,False,False,True,2015-07-10,179,51,38,239.554,31,0,0,0,2,7,4
6,False,False,False,True,2015-07-17,361,52,28,239.554,27,0,1,4,8,7,4
7,False,False,False,True,2015-07-24,260,50,36,239.554,23,0,4,0,4,7,4
8,False,False,True,False,2015-07-06,155,12,34,239.554,25,0,2,0,40,7,0
9,False,False,False,True,2015-07-13,235,11,37,239.554,29,1,1,1,8,7,0
10,True,False,False,False,2015-07-20,260,50,36,239.554,23,0,4,0,8,7,0
11,True,False,False,False,2015-07-14,260,50,36,239.554,23,0,4,0,8,7,1
12,True,False,False,False,2015-07-15,260,50,36,239.554,23,0,4,0,8,7,2
13,True,False,False,False,2015-07-15,179,51,38,239.554,31,0,0,0,1,7,2
14,False,False,False,True,2015-07-15,179,51,38,239.554,31,0,0,0,4,7,2
15,True,False,False,False,2015-07-17,246,25,41,239.554,23,0,0,0,8,7,4
16,False,False,False,True,2015-07-17,179,51,38,239.554,31,0,0,0,2,7,4
17,False,False,True,False,2015-07-27,179,51,38,239.554,31,0,0,0,8,7,0
18,True,False,False,False,2015-07-30,189,29,33,239.554,25,0,2,2,8,7,3
19,False,False,False,True,2015-08-05,248,25,47,205.917,32,0,2,1,2,8,2